#!/usr/bin/env -S bash -i

get_user() {
    secret-tool search client sieveshell workstation wintermute 2>&1 | \
    grep -E "^attribute\.UserName" | \
    cut -d " " -f3
}

get_pass() {
    secret-tool search client sieveshell workstation wintermute 2>&1 | \
    grep -E "^secret" | \
    cut -d " " -f3
}

main() {

local managesieve_address=imap-int.suse.de
local managesieve_port=4190

# If sieveshell is not installed skip this check w/o blocking the commit
type sieveshell >/dev/null 2>&1 || return 0

# This hook has to be run from there or it won't find all the sieve files
find $(git rev-parse --show-toplevel) -type f -name "*.sieve" -printf "put %p %f\n" | sort -nr | \
sieveshell --user $(get_user) \
           --passwd $(get_pass) \
           --use-tls \
           --port $managesieve_port \
           $managesieve_address
}

main
